import {NextResponse} from "next/server";import {ObjectId,type Db} from "mongodb";import {getDb} from "@/lib/db";import {getSession} from "@/lib/auth";import {z} from "zod";import productsJson from "@/data/products.json";import type {Review} from "@/types";
const createSchema=z.object({productId:z.string().min(1).max(200),rating:z.number().int().min(1).max(5),title:z.string().max(120).optional().default(""),body:z.string().min(10).max(2000)});
interface ReviewDoc{_id?:ObjectId;productId:string;userId?:string|ObjectId|null;customerName:string;rating:number;title?:string;body:string;approved:boolean;verifiedPurchase?:boolean;createdAt?:Date}
function slugOf(productId:string){return productId.startsWith("slug:")?productId.slice(5):productId}
function productIdCandidates(productId:string){const slug=slugOf(productId);return [productId,slug,`slug:${slug}`]}
function toPublicReview(d:ReviewDoc):Review{return {_id:d._id?String(d._id):"",productId:d.productId,customerName:d.customerName||"Customer",rating:d.rating,title:d.title??"",body:d.body,approved:d.approved!==false,verifiedPurchase:d.verifiedPurchase===true,createdAt:d.createdAt instanceof Date?d.createdAt.toISOString():""}}
async function hasPaidOrder(db:Db,userId:string,productId:string){if(!ObjectId.isValid(userId))return false;const order=await db.collection("orders").findOne({userId:new ObjectId(userId),paymentStatus:"paid","items.productId":{$in:productIdCandidates(productId)}},{projection:{_id:1}});return Boolean(order)}
export async function GET(req:Request){try{const productId=new URL(req.url).searchParams.get("productId")?.trim()||null;const db=await getDb();const docs=await db.collection<ReviewDoc>("reviews").find(productId?{approved:true,productId}:{approved:true}).sort({createdAt:-1}).limit(200).toArray();const pending=docs.filter(d=>typeof d.verifiedPurchase!=="boolean"&&d.userId);const verifiedByUser=new Set<string>();if(pending.length){const ids=[...new Set(pending.map(d=>String(d.userId)))].filter(id=>ObjectId.isValid(id)).map(id=>new ObjectId(id));if(ids.length){const paid=await db.collection("orders").find({userId:{$in:ids},paymentStatus:"paid",...(productId?{"items.productId":{$in:productIdCandidates(productId)}}:{})}).project({userId:1}).toArray();for(const o of paid){const uid=o.userId?String(o.userId):"";if(uid)verifiedByUser.add(uid)}}}return NextResponse.json(docs.map(d=>{const r=toPublicReview(d);if(typeof d.verifiedPurchase!=="boolean"&&d.userId)r.verifiedPurchase=verifiedByUser.has(String(d.userId));return r}))}catch{return NextResponse.json({error:"Database unavailable"},{status:503})}}
export async function POST(req:Request){try{const user=await getSession();if(!user)return NextResponse.json({error:"Please sign in to write a review."},{status:401});const p=createSchema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Invalid review. Rating must be 1-5 and review text 10-2000 characters."},{status:400});const db=await getDb();const slug=slugOf(p.data.productId);let exists=false;if(ObjectId.isValid(p.data.productId))exists=Boolean(await db.collection("products").findOne({_id:new ObjectId(p.data.productId)},{projection:{_id:1}}));if(!exists)exists=Boolean(await db.collection("products").findOne({slug},{projection:{_id:1}}));if(!exists)exists=productsJson.some((item:{slug:string})=>item.slug===slug);if(!exists)return NextResponse.json({error:"Artwork not found."},{status:404});const duplicate=await db.collection<ReviewDoc>("reviews").findOne({productId:p.data.productId,userId:user.id});if(duplicate)return NextResponse.json({error:"You have already reviewed this artwork."},{status:409});const verifiedPurchase=await hasPaidOrder(db,user.id,p.data.productId);const doc:ReviewDoc={productId:p.data.productId,userId:user.id,customerName:user.name,rating:p.data.rating,title:p.data.title??"",body:p.data.body,approved:false,verifiedPurchase,createdAt:new Date()};const r=await db.collection<ReviewDoc>("reviews").insertOne(doc);return NextResponse.json({ok:true,id:String(r.insertedId),message:"Thank you! Your review was submitted and is pending moderation."},{status:201})}catch{return NextResponse.json({error:"Could not submit review."},{status:500})}}
